apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-project
  template:
    metadata:
      labels:
        app: minikube-project
    spec:
      containers:
      - name: minikube-project
        image: client-image:v1
        ports:
        - containerPort: 3000